### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by rahul-nt** [jenkspt/recycle#1]
Hi

Is it possible to get the dataset for object detection?

**Comment by jenkspt** [comment]
Hey I'm sorry for missing this request from over a year ago. The dataset is available via the `data_utils.py` file. Here's the link to the Labelbox download url: [https://storage.googleapis.com/labelbox-exports/cjnxo84x0j9dh0797j4fnrf76/cjny1mlmn834y08762g947hm1/export-coco-2018-11-16T23%3A07%3A41.142812.json](https://storage.googleapis.com/labelbox-exports/cjnxo84x0j9dh0797j4fnrf76/cjny1mlmn834y08762g947hm1/export-coco-2018-11-16T23%3A07%3A41.142812.json ). Hope it's still useful
